apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    author: naresh
  annotations: 
    org.docker.kubernetes.image.maintainer: naresh
    
spec:
  containers:
    - image: nginx
      name: nginx
