apiVersion: v1
kind: Pod
metadata: 
  name: multicontainer
  namespace: roboshop
spec:
  containers:
    - image: nginx
      name: nginx
    - image: almalinux
      name: side-car
      command: ["sleep","200"]