apiVersion: v1
kind: Pod
metadata: 
  name: secret-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: username
          valueFrom: 
            secretKeyRef:
              name: mysecrets
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: mysecrets
              key: password
  restartPolicy: never
