apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          valueFrom:
            configMapKeyRef:
              name: config-resource
              key: course
        - name: duration
          valueFrom:
            configMapKeyRef:
              name: config-resource
              key: duration
