apiVersion: v1
kind: Pod
metadata:
  name: probe
spec:
  containers:
    - name: probe
      image: nginx
      livenessProbe: 
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 5