---

apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    server_name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

---
        
apiVersion: v1
kind: Service
metadata:
  name: nginx-service  
spec:
  type: NodePort
  selector:
    server_name: nginx
  ports:
    - protocal: tcp
      port: 80
      targetPort: 80
